version: 0.5.1.{build}

install:
 - curl -o scons.zip -fsS http://vorboss.dl.sourceforge.net/project/scons/scons/2.4.0/scons-2.4.0.zip
 - unzip scons.zip

build_script:
 - python scons-2.4.0/script/scons
