name: CI

on:
  push:
    branches:
      - 'master'

  pull_request:
    branches:
      - 'master'

jobs:
  androidBuild:
    defaults:
      run:
        working-directory: ./src/android

    name: Android build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Assemble app debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload app APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: src/android/RHVoice-core/build/outputs/apk/debug/RHVoice-core-debug.apk

  linuxBuild:
    name: Linux build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install build dependencies
        run: |
          sudo apt-get -q -y update
          sudo apt-get -q -y install scons libpulse-dev libao-dev portaudio19-dev libspeechd-dev

      - name: build
        run: scons -j2

  windowsBuild:
    name: Windows build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install build dependencies
        run: python -m pip install --upgrade pip lxml scons

      - name: build
        run: scons -j2

      - name: Upload packages archive
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: build/windows/packages
